# Blightstone CRM - Local Development Configuration
# Simple, clean config with only what we need

project_id = "blightstone"

[api]
enabled = true
port = 54323
schemas = ["public"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
enable_signup = true
minimum_password_length = 6

[auth.email]
enable_signup = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "50MiB"

[inbucket]
enabled = false

[realtime]
enabled = false

[analytics]
enabled = false

[edge_runtime]
enabled = false