import type { Transaction } from "@/types/transaction"

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    type: "wallet_topup",
    amount: 5000.0,
    fee: 50.0,
    description: "Wallet top-up via credit card",
    status: "completed",
    timestamp: "2024-06-09T14:30:00Z",
    reference: "REF-001-2024",
    destination: {
      id: "wallet_main",
      name: "Main Wallet",
      type: "wallet",
    },
  },
  {
    id: "txn_002",
    type: "business_transfer",
    amount: 2000.0,
    description: "Transfer to E-commerce Business",
    status: "completed",
    timestamp: "2024-06-08T10:15:00Z",
    reference: "REF-002-2024",
    source: {
      id: "wallet_main",
      name: "Main Wallet",
      type: "wallet",
    },
    destination: {
      id: "bus_001",
      name: "E-commerce Business",
      type: "business",
    },
    businessId: "bus_001",
    businessName: "E-commerce Business",
  },
  {
    id: "txn_003",
    type: "account_topup",
    amount: 1000.0,
    description: "Top-up to Primary Campaign Account",
    status: "completed",
    timestamp: "2024-06-07T16:45:00Z",
    reference: "REF-003-2024",
    source: {
      id: "bus_001",
      name: "E-commerce Business",
      type: "business",
    },
    destination: {
      id: "acc_001",
      name: "Primary Campaign Account",
      type: "account",
    },
    businessId: "bus_001",
    businessName: "E-commerce Business",
    accountId: "acc_001",
    accountName: "Primary Campaign Account",
  },
  {
    id: "txn_004",
    type: "ad_spend",
    amount: 250.0,
    description: "Ad spend - Summer Campaign",
    status: "completed",
    timestamp: "2024-06-06T09:00:00Z",
    reference: "REF-004-2024",
    source: {
      id: "acc_001",
      name: "Primary Campaign Account",
      type: "account",
    },
    businessId: "bus_001",
    businessName: "E-commerce Business",
    accountId: "acc_001",
    accountName: "Primary Campaign Account",
  },
  {
    id: "txn_005",
    type: "wallet_withdrawal",
    amount: 1000.0,
    description: "Withdrawal to bank account",
    status: "pending",
    timestamp: "2024-06-05T11:20:00Z",
    reference: "REF-005-2024",
    source: {
      id: "wallet_main",
      name: "Main Wallet",
      type: "wallet",
    },
    destination: {
      id: "bank_001",
      name: "Bank Account ****5678",
      type: "external",
    },
  },
  {
    id: "txn_006",
    type: "refund",
    amount: 150.0,
    description: "Campaign refund - Cancelled promotion",
    status: "completed",
    timestamp: "2024-06-04T13:30:00Z",
    reference: "REF-006-2024",
    source: {
      id: "acc_002",
      name: "Seasonal Campaign Account",
      type: "account",
    },
    destination: {
      id: "bus_002",
      name: "Brand Marketing Business",
      type: "business",
    },
    businessId: "bus_002",
    businessName: "Brand Marketing Business",
    accountId: "acc_002",
    accountName: "Seasonal Campaign Account",
  },
  {
    id: "txn_007",
    type: "business_transfer",
    amount: 3000.0,
    description: "Transfer to Brand Marketing Business",
    status: "failed",
    timestamp: "2024-06-03T15:45:00Z",
    reference: "REF-007-2024",
    source: {
      id: "wallet_main",
      name: "Main Wallet",
      type: "wallet",
    },
    destination: {
      id: "bus_002",
      name: "Brand Marketing Business",
      type: "business",
    },
    businessId: "bus_002",
    businessName: "Brand Marketing Business",
  },
  {
    id: "txn_008",
    type: "ad_spend",
    amount: 750.0,
    description: "Ad spend - Product Launch Campaign",
    status: "completed",
    timestamp: "2024-06-02T08:45:00Z",
    reference: "REF-008-2024",
    source: {
      id: "acc_003",
      name: "Product Launch Account",
      type: "account",
    },
    businessId: "bus_001",
    businessName: "E-commerce Business",
    accountId: "acc_003",
    accountName: "Product Launch Account",
  },
]
