services:
  # Staging Backend
  - type: web
    name: adhub-backend-staging
    env: python
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: pip install -r requirements/prod.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --forwarded-allow-ips '*'
    envVars:
      - key: ENVIRONMENT
        value: staging
      - key: SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://staging.adhub.tech,https://www.staging.adhub.tech"
      - key: DOLPHIN_API_URL
        value: https://cloud.dolphin.tech
      - key: DOLPHIN_API_KEY
        sync: false  # Set manually in Render dashboard - same as production Dolphin token

  # Staging Frontend
  - type: web
    name: adhub-frontend-staging
    env: node
    region: oregon
    plan: starter
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://adhub-backend-staging.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard
      - key: NEXT_PUBLIC_ENVIRONMENT
        value: staging

  # Staging Telegram Bot
  - type: web
    name: adhub-telegram-bot-staging
    env: python
    region: oregon
    plan: starter
    rootDir: telegram-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bot.py
    envVars:
      - key: ENVIRONMENT
        value: staging
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Set manually - use different bot for staging
      - key: SUPABASE_URL
        sync: false  # Same as staging backend
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Same as staging backend
      - key: DOLPHIN_CLOUD_BASE_URL
        value: https://cloud.dolphin.tech
      - key: DOLPHIN_CLOUD_TOKEN
        sync: false  # Set manually in Render dashboard
      - key: ADMIN_USER_IDS
        sync: false  # Your Telegram ID: 7723014090 