// Content tokens for consistent messaging across the application
export const contentTokens = {
  // Common actions
  actions: {
    save: "Save",
    cancel: "Cancel", 
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    update: "Update",
    confirm: "Confirm",
    close: "Close",
    back: "Back",
    next: "Next",
    submit: "Submit",
    retry: "Retry",
    refresh: "Refresh",
    copy: "Copy",
    download: "Download",
    upload: "Upload",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    export: "Export",
    import: "Import",
    connect: "Connect",
    disconnect: "Disconnect",
    enable: "Enable",
    disable: "Disable",
    activate: "Activate",
    deactivate: "Deactivate",
    invite: "Invite",
    remove: "Remove",
    add: "Add",
    view: "View",
    manage: "Manage",
    apply: "Apply",
    distribute: "Distribute",
    consolidate: "Consolidate",
    withdraw: "Withdraw",
    topUp: "Top-up",
    pause: "Pause",
    resume: "Resume",
    archive: "Archive",
    share: "Share",
    configure: "Configure",
  },

  // Loading states
  loading: {
    default: "Loading...",
    saving: "Saving...",
    creating: "Creating...",
    deleting: "Deleting...",
    uploading: "Uploading...",
    processing: "Processing...",
    connecting: "Connecting...",
    syncing: "Syncing...",
    validating: "Validating...",
  },

  // Success messages
  success: {
    saved: "Changes saved successfully",
    deleted: "Item deleted successfully",
    created: "Item created successfully",
    updated: "Item updated successfully",
    uploaded: "File uploaded successfully",
    copied: "Copied to clipboard",
    invited: "Invitation sent successfully",
    connected: "Account connected successfully",
    disconnected: "Account disconnected successfully",
    exported: "Data exported successfully",
    imported: "Data imported successfully",
    funded: "Account funded successfully",
    transferred: "Transfer completed",
    paused: "Account paused",
    resumed: "Account resumed",
    archived: "Account archived",
    topUpCompleted: "Top-up completed",
    paymentProcessed: "Payment processed",
    businessCreated: "Business application submitted",
    businessApproved: "Business approved",
  },

  // Error messages
  errors: {
    generic: "Something went wrong. Please try again.",
    network: "Network error. Please check your connection.",
    unauthorized: "You don't have permission to perform this action.",
    notFound: "The requested item was not found.",
    validation: "Please check your input and try again.",
    required: "This field is required",
    invalidEmail: "Please enter a valid email address",
    invalidPassword: "Password must be at least 8 characters",
    passwordMismatch: "Passwords do not match",
    fileTooLarge: "File size is too large",
    invalidFileType: "Invalid file type",
    uploadFailed: "File upload failed",
    saveFailed: "Failed to save changes",
    deleteFailed: "Failed to delete item",
    connectionFailed: "Failed to establish connection",
    invalidAmount: "Please enter a valid amount",
    insufficientFunds: "Insufficient funds",
    networkError: "Network error occurred",
    serverError: "Server error occurred",
    validationFailed: "Validation failed",
    operationFailed: "Operation failed",
    accountNotFound: "Account not found",
    businessNotFound: "Business not found",
  },

  // Empty states
  empty: {
    noData: "No data available",
    noResults: "No results found",
    noAccounts: "No accounts found",
    noBusinesses: "No businesses found",
    noTransactions: "No transactions found",
    noTeamMembers: "No team members found",
    noNotifications: "No notifications",
    searchNoResults: "No results match your search",
    filterNoResults: "No items match your filters",
    noBusiness: "No business selected",
    noActivity: "No recent activity",
    getStarted: "Get started by creating your first",
    tryAdjusting: "Try adjusting your search or filters",
  },

  // Confirmation messages
  confirmations: {
    delete: "Are you sure you want to delete this item?",
    deleteAccount: "Are you sure you want to delete this account?",
    deleteBusiness: "Are you sure you want to delete this business?",
    removeTeamMember: "Are you sure you want to remove this team member?",
    unsavedChanges: "You have unsaved changes. Are you sure you want to leave?",
    permanentAction: "This action cannot be undone.",
  },

  // Placeholders
  placeholders: {
    search: "Search...",
    email: "Enter email address",
    password: "Enter password",
    name: "Enter name",
    description: "Enter description",
    amount: "Enter amount",
    selectOption: "Select an option",
    chooseFile: "Choose file",
    typeToSearch: "Type to search",
    enterText: "Enter text",
    organizationName: "Enter organization name",
    searchAccounts: "Search ad accounts...",
    searchBusinesses: "Search businesses...",
    enterAmount: "Enter amount",
    selectPaymentMethod: "Select payment method",
    typeToConfirm: "Type to confirm",
    noData: "No data available",
    loading: "Loading...",
    selectBusiness: "Select a business",
    enterBusinessName: "Enter business name",
    selectTimezone: "Select timezone",
    enterWebsite: "Enter website URL",
  },

  // Status labels
  status: {
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    enabled: "Enabled",
    disabled: "Disabled",
    connected: "Connected",
    disconnected: "Disconnected",
    verified: "Verified",
    unverified: "Unverified",
    paused: "Paused",
    rejected: "Rejected",
    approved: "Approved",
    processing: "Processing",
    warning: "Warning",
    info: "Info",
    idle: "Idle",
    suspended: "Suspended",
  },

  // Navigation
  navigation: {
    dashboard: "Dashboard",
    accounts: "Accounts",
    businesses: "Businesses", 
    wallet: "Wallet",
    settings: "Settings",
    profile: "Profile",
    team: "Team",
    billing: "Billing",
    security: "Security",
    notifications: "Notifications",
    help: "Help",
    support: "Support",
    documentation: "Documentation",
    logout: "Logout",
    reports: "Reports",
  },

  // Form labels
  labels: {
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    phoneNumber: "Phone Number",
    company: "Company",
    role: "Role",
    permissions: "Permissions",
    description: "Description",
    amount: "Amount",
    currency: "Currency",
    date: "Date",
    time: "Time",
    timezone: "Timezone",
    language: "Language",
    country: "Country",
    address: "Address",
    city: "City",
    state: "State",
    zipCode: "ZIP Code",
    balance: "Balance",
    dateCreated: "Date Created",
    lastActive: "Last Active",
    totalSpend: "Total Spend",
    spendLimit: "Spend Limit",
    businessName: "Business Name",
    website: "Website",
    industry: "Industry",
    accountId: "Account ID",
    bmId: "BM ID",
    spendToday: "Today's Spend",
    accountsCount: "Accounts",
    totalBalance: "Total Balance",
    allocatedFunds: "Allocated Funds",
    unallocatedFunds: "Unallocated",
    utilization: "Utilization",
    monthlySpend: "Monthly Spend",
    dailyAverage: "Daily Average",
    peakDaySpend: "Peak Day Spend",
    change24h: "24h Change",
    change7d: "7d Change",
  },

  // Tooltips and help text
  help: {
    required: "This field is required",
    optional: "This field is optional",
    passwordRequirements: "Password must be at least 8 characters with uppercase, lowercase, and numbers",
    emailFormat: "Please enter a valid email address",
    phoneFormat: "Please enter a valid phone number",
    fileUpload: "Drag and drop files here or click to browse",
    maxFileSize: "Maximum file size: 10MB",
    supportedFormats: "Supported formats: JPG, PNG, PDF",
  },

  // Wallet and financial actions
  financial: {
    addFunds: "Add Funds", 
    withdraw: "Withdraw",
    transfer: "Transfer",
    consolidate: "Consolidate",
    distribute: "Distribute",
    fundWallet: "Fund Wallet",
    topUpAccount: "Top-up Account",
    viewBalance: "View Balance",
    viewTransactions: "View Transactions",
    paymentMethod: "Payment Method",
    bankTransfer: "Bank Transfer",
    creditCard: "Credit Card",
    cryptocurrency: "Cryptocurrency",
  },

  // Business management actions
  business: {
    createBusiness: "Apply for Business",
    viewAccounts: "View Accounts", 
    addAccount: "Add Account",
    verifyBusiness: "Verify Business",
    businessManager: "Business Manager",
    adAccounts: "Ad Accounts",
    businessDetails: "Business Details",
  },

  // Currency and formatting
  currency: {
    usd: "USD",
    symbol: "$",
    free: "Free",
    unlimited: "Unlimited",
  },

  // Time and date formats
  time: {
    now: "Now",
    justNow: "Just now",
    minutesAgo: (minutes: number) => `${minutes}m ago`,
    hoursAgo: (hours: number) => `${hours}h ago`,
    daysAgo: (days: number) => `${days}d ago`,
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This week",
    lastWeek: "Last week",
    thisMonth: "This month",
    lastMonth: "Last month",
  },

  // Metrics and analytics
  metrics: {
    totalAccounts: "Total Accounts",
    activeAccounts: "Active Accounts",
    totalBusinesses: "Total Businesses",
    activeBusinesses: "Active Businesses",
    pendingBusinesses: "Pending",
    totalSpend: "Total Spend",
    monthlySpend: "Monthly Spend",
    weeklySpend: "Weekly Spend", 
    dailySpend: "Daily Spend",
    averageSpend: "Average Spend",
    spendTrend: "Spend Trend",
    performance: "Performance",
    efficiency: "Efficiency",
    roi: "ROI",
    ctr: "CTR",
    cpc: "CPC",
    cpm: "CPM",
    impressions: "Impressions",
    clicks: "Clicks",
    conversions: "Conversions",
  },

  // Time filters (for charts and analytics)
  timeFilters: {
    today: "Today",
    yesterday: "Yesterday", 
    last7days: "Last 7 days",
    last30days: "Last 30 days",
    last90days: "Last 90 days",
    thisMonth: "This month",
    lastMonth: "Last month",
    thisYear: "This year",
    allTime: "All time",
    custom: "Custom range",
  },

  // Table headers and sorting
  table: {
    sortAscending: "Sort ascending",
    sortDescending: "Sort descending",
    selectAll: "Select all",
    selectedItems: (count: number) => `${count} selected`,
    itemsPerPage: "Items per page",
    showingItems: (start: number, end: number, total: number) => 
      `Showing ${start}-${end} of ${total} items`,
    noDataAvailable: "No data available",
    loading: "Loading data...",
  },
}

// Utility functions for content
export const getErrorMessage = (errorType: keyof typeof contentTokens.errors, fallback?: string) => {
  return contentTokens.errors[errorType] || fallback || contentTokens.errors.generic
}

export const getSuccessMessage = (successType: keyof typeof contentTokens.success, fallback?: string) => {
  return contentTokens.success[successType] || fallback || "Operation completed successfully"
}

export const getStatusLabel = (status: string) => {
  return contentTokens.status[status as keyof typeof contentTokens.status] || status
} 